import { useState } from "react";
import { Bot, Sparkles } from "lucide-react";
import { api, jsonBody } from "../api";
import { EmptyState, Field, PageHeader, Panel } from "../components";
import type { PageProps } from "../App";

type AIResult={provider:string;model:string;content:unknown;durationMs:number};
export default function AIPage({data,go}:PageProps){const[result,setResult]=useState<AIResult|null>(null);const[busy,setBusy]=useState(false);async function analyze(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setResult(null);const payload=Object.fromEntries(new FormData(event.currentTarget));payload.applicationId=Number(payload.applicationId) as never;try{setResult(await api<AIResult>("/ai/analyze",{method:"POST",...jsonBody(payload)}));}catch(reason){window.alert(reason instanceof Error?reason.message:"分析失败");}finally{setBusy(false)}}
 return <><PageHeader eyebrow="AI ASSISTANT" title="AI 求职助手" description="自动结合岗位 JD、个人资料与经历库，完成匹配、简历建议和面试准备。"/><div className="ai-context-note"><strong>已连接个人资料库</strong><span>{data.materials.length} 条经历素材会按需随本次请求发送；敏感字段不会加入分析。</span><button className="text-button" onClick={()=>go("profile")}>管理资料</button></div><div className="ai-layout"><Panel title="开始分析" description={`当前模式：${data.settings?.config.ai.mode==="reasonix"?"Reasonix CLI":"DeepSeek API"}`}><form className="ai-form" onSubmit={analyze}><Field label="投递岗位"><select name="applicationId" required defaultValue=""><option value="" disabled>选择一条投递</option>{data.applications.map(a=><option key={a.id} value={a.id}>{a.companyName} · {a.positionName}</option>)}</select></Field><Field label="分析类型"><select name="kind" defaultValue="job_match"><option value="job_match">JD 匹配与缺口</option><option value="resume_suggestions">简历改写建议</option><option value="interview_prep">面试准备清单</option></select></Field><Field label="本次补充（可选）" hint="只填写资料库中没有、且确实与本岗位有关的信息。"><textarea name="extraContext" rows={7} placeholder="通常可以留空；AI 会自动读取已保存资料。"/></Field>{!data.settings?.apiKeyConfigured&&data.settings?.config.ai.mode!=="reasonix"&&<div className="inline-warning">尚未配置 API Key。<button type="button" className="text-button" onClick={()=>go("settings")}>前往设置</button></div>}<button className="primary-button ai-submit" disabled={busy}><Sparkles size={17}/>{busy?"正在分析…":"开始分析"}</button></form></Panel><Panel title="分析结果" description="结果是辅助判断，不替代你的事实核对。">{result?<ResultView result={result}/>:<EmptyState title="等待一次分析" description="选择岗位和用途，结果会在这里结构化展示。" action={<Bot size={30}/>}/>}</Panel></div></>}
function ResultView({result}:{result:AIResult}){const value=result.content as Record<string,unknown>;return <div className="ai-result"><div className="ai-result-meta"><span>{result.provider}</span><span>{result.model}</span><span>{(result.durationMs/1000).toFixed(1)} 秒</span></div>{Object.entries(value||{}).map(([key,item])=><section key={key}><h3>{label(key)}</h3>{Array.isArray(item)?<ul>{item.map((line,index)=><li key={index}>{typeof line==="object"?JSON.stringify(line):String(line)}</li>)}</ul>:typeof item==="object"?<pre>{JSON.stringify(item,null,2)}</pre>:<p>{String(item)}</p>}</section>)}</div>}
const label=(key:string)=>({score:"匹配分",summary:"结论",matched:"匹配证据",gaps:"缺口",actions:"下一步",risks:"风险",suggestions:"改写建议",keywords:"关键词",questions:"待确认事实",focus:"准备重点",technical:"专业问题",projectQuestions:"项目追问",companyQuestions:"反问问题",plan:"行动计划"}[key]||key);
