import { useMemo, useState } from "react";
import { Bot, Check, Clipboard, ListPlus, ShieldCheck, Sparkles } from "lucide-react";
import { api, jsonBody } from "../api";
import { EmptyState, Field, PageHeader, Panel } from "../components";
import type { PageProps } from "../App";

type AIResult={provider:string;model:string;content:unknown;durationMs:number};
const labels:Record<string,string>={score:"匹配分",summary:"结论",matched:"匹配证据",gaps:"需要补足",actions:"建议行动",risks:"面试风险",suggestions:"简历改写",keywords:"关键词",questions:"待确认事实",focus:"准备重点",technical:"专业问题",projectQuestions:"项目追问",companyQuestions:"反问问题",plan:"行动计划"};
const hashApplication=()=>Number(new URLSearchParams(window.location.hash.split("?")[1]||"").get("application")||0);
function taskLines(content:unknown){if(!content||typeof content!=="object")return[];const value=content as Record<string,unknown>;return ["actions","plan","focus"].flatMap(key=>Array.isArray(value[key])?value[key] as unknown[]:[]).filter((item):item is string=>typeof item==="string"&&Boolean(item.trim())).slice(0,8)}

export default function AIPage({data,go,refresh}:PageProps){
 const[result,setResult]=useState<AIResult|null>(null);const[busy,setBusy]=useState(false);const[copied,setCopied]=useState(false);const[applicationId,setApplicationId]=useState(hashApplication);const selected=useMemo(()=>data.applications.find(item=>item.id===applicationId),[data.applications,applicationId]);
 async function analyze(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setResult(null);const payload=Object.fromEntries(new FormData(event.currentTarget));payload.applicationId=Number(payload.applicationId) as never;try{setResult(await api<AIResult>("/ai/analyze",{method:"POST",...jsonBody(payload)}))}catch(reason){window.alert(reason instanceof Error?reason.message:"分析失败")}finally{setBusy(false)}}
 async function copy(){if(!result)return;await navigator.clipboard.writeText(JSON.stringify(result.content,null,2));setCopied(true);setTimeout(()=>setCopied(false),1600)}
 async function addTasks(){if(!result||!selected)return;const lines=taskLines(result.content);if(!lines.length){window.alert("这次结果中没有可直接加入行动清单的条目。");return}if(!window.confirm(`把 ${lines.length} 条建议加入行动清单？`))return;for(const title of lines)await api("/tasks",{method:"POST",...jsonBody({title,dueDate:"",priority:2,notes:`来自 ${selected.companyName} · ${selected.positionName} 的 AI 分析`})});await refresh();go("tasks")}
 return <><PageHeader title="岗位准备助手" description="从具体岗位出发，生成可执行的匹配、简历和面试准备建议。"/><div className="ai-context-note"><ShieldCheck size={17}/><strong>{selected?`${selected.companyName} · ${selected.positionName}`:"仅在你主动发起时发送资料"}</strong><span>{selected?`将使用已保存的 JD 和 ${data.materials.length} 条经历素材。姓名、学校、城市等资料可能随分析发送。`:"选择岗位后会明确显示本次使用的上下文；不会在后台自动分析。"}</span><button className="text-button" onClick={()=>go("profile")}>检查资料</button></div><div className="ai-layout"><Panel title="准备一次分析" description={`当前模式：${data.settings?.config.ai.mode==="reasonix"?"Reasonix CLI":"DeepSeek API"}`}><form className="ai-form" onSubmit={analyze}><Field label="投递岗位"><select name="applicationId" required value={applicationId||""} onChange={event=>setApplicationId(Number(event.target.value))}><option value="" disabled>选择一条投递</option>{data.applications.map(a=><option key={a.id} value={a.id}>{a.companyName} · {a.positionName}</option>)}</select></Field><Field label="要完成的事情"><select name="kind" defaultValue="job_match"><option value="job_match">判断匹配证据与缺口</option><option value="resume_suggestions">生成简历修改清单</option><option value="interview_prep">生成面试准备清单</option></select></Field><Field label="本次补充（可选）" hint="只补充资料库中没有、且与这个岗位直接相关的事实。"><textarea name="extraContext" rows={6} placeholder="例如：这个岗位更看重供应链项目经验"/></Field>{!data.settings?.apiKeyConfigured&&data.settings?.config.ai.mode!=="reasonix"&&<div className="inline-warning">尚未配置 API Key。<button type="button" className="text-button" onClick={()=>go("settings")}>前往设置</button></div>}<button className="primary-button ai-submit" disabled={busy||!applicationId}><Sparkles size={17}/>{busy?"正在整理岗位上下文…":"生成准备建议"}</button></form></Panel><Panel title="可执行结果" description="结果可以复制，也可以把行动项直接加入行动清单。" action={result?<div className="ai-result-actions"><button className="secondary-button" onClick={()=>void copy()}>{copied?<Check size={15}/>:<Clipboard size={15}/>} {copied?"已复制":"复制"}</button><button className="primary-button" disabled={!taskLines(result.content).length} onClick={()=>void addTasks()}><ListPlus size={15}/>加入行动清单</button></div>:undefined}>{result?<ResultView result={result}/>:<EmptyState title="从一个具体岗位开始" description="选择用途后，建议会按证据、缺口和下一步分区展示。" action={<Bot size={30}/>}/>}</Panel></div></>}

function ResultView({result}:{result:AIResult}){const value=result.content&&typeof result.content==="object"?result.content as Record<string,unknown>:{summary:String(result.content||"")};return <div className="ai-result"><div className="ai-result-meta"><span>{result.provider}</span><span>{result.model}</span><span>{(result.durationMs/1000).toFixed(1)} 秒</span></div>{Object.entries(value).map(([key,item])=><section key={key}><h3>{labels[key]||key}</h3>{Array.isArray(item)?<div className="ai-result-list">{item.map((line,index)=><article key={index}>{typeof line==="object"&&line!==null?Object.entries(line as Record<string,unknown>).map(([name,text])=><p key={name}><b>{labels[name]||name}</b><span>{String(text)}</span></p>):<p><span>{String(line)}</span></p>}</article>)}</div>:typeof item==="object"&&item!==null?<div className="ai-result-object">{Object.entries(item as Record<string,unknown>).map(([name,text])=><p key={name}><b>{labels[name]||name}</b><span>{String(text)}</span></p>)}</div>:<p>{String(item)}</p>}</section>)}</div>}
