import { useState } from "react";
import { MessageSquarePlus, Trash2 } from "lucide-react";
import { api, formatDateTime, jsonBody } from "../api";
import { ConfirmButton, EmptyState, Field, PageHeader, Panel, StatusBadge } from "../components";
import type { PageProps } from "../App";

export default function InterviewsPage({ data, refresh }: PageProps) {
  const [showForm,setShowForm]=useState(false); const active=data.interviews.filter(i=>i.result!=="未通过"); const history=data.interviews.filter(i=>i.result==="未通过"); const [showHistory,setShowHistory]=useState(false);
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const payload=Object.fromEntries(new FormData(form));payload.applicationId=Number(payload.applicationId) as never;try{await api("/interviews",{method:"POST",...jsonBody(payload)});form.reset();setShowForm(false);await refresh();}catch(reason){window.alert(reason instanceof Error?reason.message:"保存失败");}}
  return <><PageHeader eyebrow="INTERVIEW NOTES" title="面试复盘" description="复盘属于面试页，不挤占总览；结束后尽快记下细节。" action={<button className="primary-button" onClick={()=>setShowForm(v=>!v)}><MessageSquarePlus size={17}/>记录面试</button>}/>
    {showForm&&<Panel title="新增面试复盘" description="对应岗位使用清晰的原生字体与统一控件。"><form className="interview-form" onSubmit={create}><Field label="对应岗位"><select name="applicationId" required defaultValue=""><option value="" disabled>选择投递岗位</option>{data.applications.filter(a=>a.currentStatus!=="终止").map(a=><option key={a.id} value={a.id}>{a.companyName} · {a.positionName}</option>)}</select></Field><Field label="轮次"><select name="round" defaultValue="一面">{["AI 面试","一面","二面","三面","HR 面","其他"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="面试时间"><input name="interviewTime" type="datetime-local" /></Field><Field label="结果"><select name="result" defaultValue="待确认">{["待确认","通过","未通过"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="整体总结" span><textarea name="summary" rows={3}/></Field><Field label="主要问题" span><textarea name="questions" rows={5}/></Field><Field label="薄弱点"><textarea name="weakPoints" rows={4}/></Field><Field label="后续行动"><textarea name="followUp" rows={4}/></Field><div className="form-actions field-span"><button type="button" className="secondary-button" onClick={()=>setShowForm(false)}>取消</button><button className="primary-button">保存复盘</button></div></form></Panel>}
    <Panel title="近期复盘" description="未通过记录在历史区折叠，减少查找干扰。">{active.length?<div className="interview-cards">{active.map(i=><InterviewCard key={i.id} item={i} refresh={refresh}/>)}</div>:<EmptyState title="还没有面试复盘" description="完成一次面试后，把问题和薄弱点留在这里。"/>}</Panel>
    <Panel title="历史复盘" action={<button className="text-button" onClick={()=>setShowHistory(v=>!v)}>{showHistory?"收起":`展开 ${history.length} 条`}</button>}>{showHistory&&(history.length?<div className="interview-cards muted-cards">{history.map(i=><InterviewCard key={i.id} item={i} refresh={refresh}/>)}</div>:<EmptyState title="没有终止复盘" description="未通过的复盘会自动归入这里。"/>)}</Panel>
  </>;
}

function InterviewCard({item,refresh}:{item:import("../types").Interview;refresh:()=>Promise<void>}){return <article><div className="interview-card-head"><div><span>{item.round}</span><h3>{item.companyName} · {item.positionName}</h3><small>{formatDateTime(item.interviewTime||item.createdAt)}</small></div><StatusBadge value={item.result}/></div>{item.summary&&<p className="interview-summary">{item.summary}</p>}<div className="interview-details">{item.questions&&<section><h4>主要问题</h4><p>{item.questions}</p></section>}{item.weakPoints&&<section><h4>薄弱点</h4><p>{item.weakPoints}</p></section>}{item.followUp&&<section><h4>后续行动</h4><p>{item.followUp}</p></section>}</div><ConfirmButton className="text-button danger-text" confirmText="删除这条面试复盘？" onConfirm={async()=>{await api(`/interviews/${item.id}`,{method:"DELETE"});await refresh();}}><Trash2 size={14}/>删除</ConfirmButton></article>}
