import { useEffect, useMemo, useState } from "react";
import { BookOpenText, CheckCircle2, ChevronRight, PencilLine, Plus, Save, Trash2, UserRound } from "lucide-react";
import { api, jsonBody } from "../api";
import { ConfirmButton, EmptyState, Field, Modal, PageHeader, Panel } from "../components";
import type { PageProps } from "../App";
import type { Material, Profile } from "../types";

const types=["项目经历","实习经历","校园经历","获奖经历","技能证书","其他"];
const preview=(value:string)=>value.replace(/[#*|`>-]/g," ").replace(/\s+/g," ").trim().slice(0,180);

export default function ProfileV2Page({data,refresh}:PageProps){
 const[profile,setProfile]=useState<Profile>(data.profile);const[editing,setEditing]=useState<Material|"new"|null>(null);const[busy,setBusy]=useState(false);useEffect(()=>setProfile(data.profile),[data.profile]);
 const filled=[profile.fullName,profile.targetRole,profile.education,profile.school,profile.major,profile.city,profile.email,profile.summary].filter(v=>v.trim()).length;const completeness=Math.round(filled/8*100);
 const grouped=useMemo(()=>types.map(type=>({type,items:data.materials.filter(item=>item.materialType===type)})).filter(group=>group.items.length),[data.materials]);
 const change=(key:keyof Profile,value:string)=>setProfile({...profile,[key]:value});
 async function saveProfile(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{await api("/profile",{method:"PUT",...jsonBody(profile)});await refresh();}catch(reason){alert(reason instanceof Error?reason.message:"保存失败")}finally{setBusy(false)}}
 async function saveMaterial(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));try{editing==="new"?await api("/materials",{method:"POST",...jsonBody(payload)}):editing&&await api(`/materials/${editing.id}`,{method:"PATCH",...jsonBody(payload)});setEditing(null);await refresh()}catch(reason){alert(reason instanceof Error?reason.message:"保存失败")}}
 return <><PageHeader title="个人资料库" description="按类型折叠真实素材；AI 分析时复用，不必每次重新粘贴。" action={<button className="primary-button" onClick={()=>setEditing("new")}><Plus size={16}/>添加经历</button>}/>
 <div className="profile-v2-layout"><aside className="profile-rail"><div className="profile-completeness"><div style={{"--progress":`${completeness*3.6}deg`} as React.CSSProperties}><strong>{completeness}%</strong></div><span><b>资料完整度</b><small>{filled}/8 项基础资料已填写</small></span></div><div className="profile-identity"><span><UserRound/></span><h3>{profile.fullName||"未填写姓名"}</h3><p>{profile.targetRole||"设置你的目标方向"}</p><small>{[profile.school,profile.major].filter(Boolean).join(" · ")||"学校与专业待补充"}</small></div><div className="material-counts">{types.map(type=><span key={type}><i>{type}</i><b>{data.materials.filter(item=>item.materialType===type).length}</b></span>)}</div></aside>
 <main className="profile-content"><details className="profile-section profile-basics"><summary><span><strong>基础资料</strong><small>稳定信息与个人概述</small></span><ChevronRight/></summary><form onSubmit={saveProfile}><div className="settings-form profile-form"><Field label="姓名"><input value={profile.fullName} onChange={e=>change("fullName",e.target.value)}/></Field><Field label="目标方向"><input value={profile.targetRole} onChange={e=>change("targetRole",e.target.value)}/></Field><Field label="学历"><input value={profile.education} onChange={e=>change("education",e.target.value)}/></Field><Field label="学校"><input value={profile.school} onChange={e=>change("school",e.target.value)}/></Field><Field label="专业"><input value={profile.major} onChange={e=>change("major",e.target.value)}/></Field><Field label="所在城市"><input value={profile.city} onChange={e=>change("city",e.target.value)}/></Field><Field label="邮箱"><input type="email" value={profile.email} onChange={e=>change("email",e.target.value)}/></Field><Field label="GitHub"><input type="url" value={profile.githubUrl} onChange={e=>change("githubUrl",e.target.value)}/></Field><Field label="作品集" span><input type="url" value={profile.portfolioUrl} onChange={e=>change("portfolioUrl",e.target.value)}/></Field><Field label="个人概述" span><textarea rows={5} value={profile.summary} onChange={e=>change("summary",e.target.value)}/></Field></div><div className="modal-actions"><button className="primary-button" disabled={busy}><Save size={15}/>{busy?"保存中…":"保存基础资料"}</button></div></form></details>
 {grouped.length?grouped.map(group=><details className="profile-section" key={group.type} open><summary><span><strong>{group.type}</strong><small>{group.items.length} 条可复用素材</small></span><b>{group.items.length}</b><ChevronRight/></summary><div className="structured-material-list">{group.items.map(item=><button key={item.id} onClick={()=>setEditing(item)}><span className="material-check"><CheckCircle2 size={17}/></span><span><strong>{item.title}</strong><small>{[item.startTime,item.endTime].filter(Boolean).join(" — ")||"未填写时间"}</small><p>{preview(item.content)||"尚未填写详细事实与成果"}</p><em>{item.tags.split(/[,，]/).map(v=>v.trim()).filter(Boolean).slice(0,4).map(tag=><i key={tag}>{tag}</i>)}</em></span><PencilLine size={15}/></button>)}</div></details>):<Panel><EmptyState title="还没有经历素材" description="先添加最熟悉的一段项目或实习经历。" action={<button className="secondary-button" onClick={()=>setEditing("new")}><BookOpenText size={15}/>添加第一条</button>}/></Panel>}
 </main></div>
 {editing&&<Modal title={editing==="new"?"添加经历素材":"编辑经历素材"} subtitle="记录可在面试中自洽说明的真实事实、动作和结果。" onClose={()=>setEditing(null)} wide><form onSubmit={saveMaterial}><div className="modal-form-grid"><Field label="类型"><select name="materialType" defaultValue={editing==="new"?"项目经历":editing.materialType}>{types.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="标题"><input name="title" required autoFocus defaultValue={editing==="new"?"":editing.title}/></Field><Field label="开始时间"><input name="startTime" type="month" defaultValue={editing==="new"?"":editing.startTime}/></Field><Field label="结束时间"><input name="endTime" type="month" defaultValue={editing==="new"?"":editing.endTime}/></Field><Field label="标签" span><input name="tags" defaultValue={editing==="new"?"":editing.tags}/></Field><Field label="事实与成果" span><textarea name="content" required rows={10} defaultValue={editing==="new"?"":editing.content}/></Field></div><div className="modal-actions">{editing!=="new"&&<ConfirmButton confirmText={`确定删除“${editing.title}”？`} onConfirm={async()=>{await api(`/materials/${editing.id}`,{method:"DELETE"});setEditing(null);await refresh()}}><Trash2 size={14}/>删除</ConfirmButton>}<span className="action-spacer"/><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>取消</button><button className="primary-button">保存经历</button></div></form></Modal>}
 </>;
}
