import { useEffect, useMemo, useState } from "react";
import { BookOpenText, CheckCircle2, ChevronRight, PencilLine, Plus, Save, Search, Trash2, UserRound } from "lucide-react";
import { api, jsonBody } from "../api";
import { ConfirmButton, EmptyState, Field, Modal, PageHeader, Panel } from "../components";
import type { PageProps } from "../App";
import type { Material, Profile } from "../types";

const types=["教育经历","项目经历","实习经历","校园经历","STAR 故事","自我介绍","求职动机","获奖经历","技能证书","其他"];
const preview=(value:string)=>value.replace(/[#*|`>-]/g," ").replace(/\s+/g," ").trim().slice(0,180);

export default function ProfileV2Page({data,refresh}:PageProps){
 const[profile,setProfile]=useState<Profile>(data.profile);const[editing,setEditing]=useState<Material|"new"|null>(null);const[busy,setBusy]=useState(false);const[query,setQuery]=useState("");const[typeFilter,setTypeFilter]=useState("全部素材");useEffect(()=>setProfile(data.profile),[data.profile]);
 const filled=[profile.fullName,profile.targetRole,profile.education,profile.school,profile.major,profile.city,profile.email,profile.summary].filter(v=>v.trim()).length;const completeness=Math.round(filled/8*100);
 const grouped=useMemo(()=>types.map(type=>({type,items:data.materials.filter(item=>item.materialType===type).filter(item=>!query||`${item.title} ${item.content} ${item.tags}`.toLowerCase().includes(query.toLowerCase()))})).filter(group=>group.items.length&&(typeFilter==="全部素材"||group.type===typeFilter)),[data.materials,query,typeFilter]);
 const change=(key:keyof Profile,value:string)=>setProfile({...profile,[key]:value});
 async function saveProfile(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{await api("/profile",{method:"PUT",...jsonBody(profile)});await refresh();}catch(reason){alert(reason instanceof Error?reason.message:"保存失败")}finally{setBusy(false)}}
 async function saveMaterial(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const payload=Object.fromEntries(new FormData(event.currentTarget));try{editing==="new"?await api("/materials",{method:"POST",...jsonBody(payload)}):editing&&await api(`/materials/${editing.id}`,{method:"PATCH",...jsonBody(payload)});setEditing(null);await refresh()}catch(reason){alert(reason instanceof Error?reason.message:"保存失败")}}
 return <><PageHeader title="个人资料库" description="把教育、项目和可复用故事整理成结构化素材，按岗位快速取用。" action={<button className="primary-button" onClick={()=>setEditing("new")}><Plus size={16}/>添加素材</button>}/>
 <div className="profile-v2-layout"><aside className="profile-rail"><div className="profile-completeness"><div style={{"--progress":`${completeness*3.6}deg`} as React.CSSProperties}><strong>{completeness}%</strong></div><span><b>资料完整度</b><small>{filled}/8 项基础资料已填写</small></span></div><div className="profile-identity"><span><UserRound/></span><h3>{profile.fullName||"未填写姓名"}</h3><p>{profile.targetRole||"设置你的目标方向"}</p><small>{[profile.school,profile.major].filter(Boolean).join(" · ")||"学校与专业待补充"}</small></div><div className="material-counts">{types.map(type=><span key={type}><i>{type}</i><b>{data.materials.filter(item=>item.materialType===type).length}</b></span>)}</div></aside>
 <main className="profile-content"><details className="profile-section profile-basics"><summary><span><strong>基础资料</strong><small>姓名、教育背景、目标方向与个人概述</small></span><ChevronRight/></summary><form onSubmit={saveProfile}><div className="settings-form profile-form"><Field label="姓名"><input value={profile.fullName} onChange={e=>change("fullName",e.target.value)}/></Field><Field label="目标方向"><input value={profile.targetRole} onChange={e=>change("targetRole",e.target.value)}/></Field><Field label="学历"><input value={profile.education} onChange={e=>change("education",e.target.value)}/></Field><Field label="学校"><input value={profile.school} onChange={e=>change("school",e.target.value)}/></Field><Field label="专业"><input value={profile.major} onChange={e=>change("major",e.target.value)}/></Field><Field label="所在城市"><input value={profile.city} onChange={e=>change("city",e.target.value)}/></Field><Field label="邮箱"><input type="email" value={profile.email} onChange={e=>change("email",e.target.value)}/></Field><Field label="GitHub"><input type="url" value={profile.githubUrl} onChange={e=>change("githubUrl",e.target.value)}/></Field><Field label="作品集" span><input type="url" value={profile.portfolioUrl} onChange={e=>change("portfolioUrl",e.target.value)}/></Field><Field label="个人概述" span><textarea rows={5} value={profile.summary} onChange={e=>change("summary",e.target.value)}/></Field></div><div className="modal-actions"><button className="primary-button" disabled={busy}><Save size={15}/>{busy?"保存中…":"保存基础资料"}</button></div></form></details>
 <div className="profile-library-toolbar"><label className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索经历、成果或标签"/></label><select className="compact-select" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option>全部素材</option>{types.map(type=><option key={type}>{type}</option>)}</select><span>{data.materials.length} 条素材</span></div>
 {grouped.length?grouped.map(group=><details className="profile-section" key={group.type}><summary><span><strong>{group.type}</strong><small>{group.items.length} 条可复用素材</small></span><b>{group.items.length}</b><ChevronRight/></summary><div className="structured-material-list">{group.items.map(item=><button key={item.id} onClick={()=>setEditing(item)}><span className="material-check"><CheckCircle2 size={17}/></span><span><strong>{item.title}</strong><small>{[item.startTime,item.endTime].filter(Boolean).join(" — ")||"未填写时间"}</small><p>{preview(item.content)||"尚未填写详细事实、行动与成果"}</p><em>{item.tags.split(/[,，]/).map(v=>v.trim()).filter(Boolean).slice(0,4).map(tag=><i key={tag}>{tag}</i>)}</em></span><PencilLine size={15}/></button>)}</div></details>):<Panel><EmptyState title={query||typeFilter!=="全部素材"?"没有符合条件的素材":"还没有经历素材"} description={query||typeFilter!=="全部素材"?"换一个关键词或素材类型。":"先添加最熟悉的一段项目、实习或 STAR 故事。"} action={<button className="secondary-button" onClick={()=>{if(query||typeFilter!=="全部素材"){setQuery("");setTypeFilter("全部素材")}else setEditing("new")}}><BookOpenText size={15}/>{query||typeFilter!=="全部素材"?"清除筛选":"添加第一条"}</button>}/></Panel>}
 </main></div>
 {editing&&<Modal title={editing==="new"?"添加资料素材":"编辑资料素材"} subtitle="记录能够自洽说明的背景、行动、结果和量化证据。" onClose={()=>setEditing(null)} wide><form onSubmit={saveMaterial}><div className="modal-form-grid"><Field label="类型"><select name="materialType" defaultValue={editing==="new"?"项目经历":editing.materialType}>{types.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="标题"><input name="title" required autoFocus defaultValue={editing==="new"?"":editing.title}/></Field><Field label="开始时间"><input name="startTime" type="month" defaultValue={editing==="new"?"":editing.startTime}/></Field><Field label="结束时间"><input name="endTime" type="month" defaultValue={editing==="new"?"":editing.endTime}/></Field><Field label="能力与岗位标签" hint="例如：跨团队协作、供应链、项目管理" span><input name="tags" defaultValue={editing==="new"?"":editing.tags}/></Field><Field label="背景、行动与成果" hint="建议按“背景—任务—行动—结果—量化证据”记录；只写能够在面试中解释的真实内容。" span><textarea name="content" required rows={10} defaultValue={editing==="new"?"":editing.content}/></Field></div><div className="modal-actions">{editing!=="new"&&<ConfirmButton confirmText={`确定删除“${editing.title}”？`} onConfirm={async()=>{await api(`/materials/${editing.id}`,{method:"DELETE"});setEditing(null);await refresh()}}><Trash2 size={14}/>删除</ConfirmButton>}<span className="action-spacer"/><button type="button" className="secondary-button" onClick={()=>setEditing(null)}>取消</button><button className="primary-button">保存素材</button></div></form></Modal>}
 </>;
}
