import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
const require = createRequire(new URL('../frontend/package.json', import.meta.url));
const ts = require('typescript');
const compile = name => ts.transpileModule(readFileSync(new URL(`../frontend/src/${name}.ts`, import.meta.url), 'utf8'), { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const taxURL = `data:text/javascript;base64,${Buffer.from(compile('offerTax')).toString('base64')}`;
const code = compile('incomePlans').replace('"./offerTax"', JSON.stringify(taxURL));
const { fromOffer, incomeSummary, incomeConditions, normalizeIncome } = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
const offer = { monthlySalary: 15000, salaryMonths: 13, bonus: 0, signingBonus: 0, otherCompensation: 0 };
const defaultPlan = fromOffer(offer);
assert.equal(defaultPlan.tax.fundRate, 5);
assert.equal(defaultPlan.confirmed, false);
const custom = { ...defaultPlan, tax: { ...defaultPlan.tax, fundRate: 8, fundBase: 12000 }, employerFundRate: 12, fundBaseMode: 'custom', confirmed: true };
const reloaded = fromOffer({ ...offer, incomeSettings: JSON.stringify(incomeConditions(custom)) });
assert.equal(reloaded.tax.fundRate, 8);
assert.equal(reloaded.employerFundRate, 12);
assert.equal(reloaded.socialBaseMode, 'salary');
assert.equal(reloaded.fundBaseMode, 'custom');
assert.equal(incomeSummary(reloaded).fund.monthly, 2400);
assert.equal(incomeSummary(reloaded).tax.socialBase, 15000);
assert.deepEqual(incomeSummary(reloaded), incomeSummary(normalizeIncome(JSON.parse(JSON.stringify(reloaded)))));
assert.equal(fromOffer({ ...offer, incomeSettings: JSON.stringify(incomeConditions({ ...custom, tax: { ...custom.tax, fundRate: 0 }, employerFundRate: 0 })) }).tax.fundRate, 0);
const legacy = fromOffer({ ...offer, taxSettings: JSON.stringify({ enabled: true, year: 2026, fundRate: 7, fundBase: 9000, socialRate: 10, socialBase: 10000 }) });
assert.equal(legacy.fundBaseMode, 'custom');
assert.equal(legacy.tax.fundRate, 7);
assert.equal(legacy.confirmed, false);
assert.equal(normalizeIncome({ ...defaultPlan, socialBaseMode: undefined, fundBaseMode: undefined, customBases: true }).fundBaseMode, 'custom');
const badHours = incomeSummary({ ...custom, hours: 0 });
assert.equal(badHours.result.error, undefined);
assert.equal(badHours.hourly, null);
const badEmployer = incomeSummary({ ...custom, employerFundRate: 101 });
assert.equal(badEmployer.result.error, undefined);
assert.ok(badEmployer.fund.error);
assert.equal(incomeSummary({ ...custom, tax: { ...custom.tax, year: 2028, separateBonus: 15000 }, bonusEligible: true, method: 'combined' }).result.error, undefined);
console.log('Passed Offer → income → saved snapshot, independent bases, explicit zero, legacy conditions and localized errors.');
