import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { createRequire } from "node:module";
const require = createRequire(new URL("../frontend/package.json", import.meta.url));
const ts = require("typescript");
const source = readFileSync(new URL("../frontend/src/interviewProgress.ts", import.meta.url), "utf8");
const js = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { applicationInterviewProgress: progress, applicationInterviewStateLabel: label, preferredInterview, effectiveStageState } = await import(`data:text/javascript;base64,${Buffer.from(js).toString("base64")}`);
const app = { id: 1, currentStatus: "业务面试" };
const record = (id, round, result, interviewTime = "") => ({ id, applicationId: 1, round, result, interviewTime, createdAt: `2026-09-${10 + id}T10:00:00+08:00` });
const first = record(1, "一面", "通过", "2099-09-01T10:00:00+08:00");
const second = record(2, "二面", "待面试");
assert.equal(preferredInterview([first, second]).id, 2, "undated next round wins over previous dated round");
assert.equal(progress(app, [first, second]).kind, "unscheduled");
assert.equal(progress(app, [first]).kind, "next-round");
assert.equal(label(app, [first]), "本轮通过，等待后续通知");
assert.equal(progress({ ...app, currentStatus: "HR 面" }, [first]).nextRound, "HR 面");
assert.equal(progress({ ...app, currentStatus: "HR 面" }, [first]).interview, undefined);
assert.equal(progress(app, [record(1, "AI 面试", "待确认")]).kind, "unscheduled");
assert.equal(progress(app, [record(1, "一面", "待确认")]).kind, "waiting");
assert.equal(progress(app, [record(1, "一面", "待面试", "2026-09-20T10:00")]).kind, "scheduled");
assert.equal(progress({ ...app, currentStatus: "终止" }, [second]).kind, "history");
assert.equal(progress({ ...app, currentStatus: "Offer" }, [second]).kind, "history");
assert.equal(progress(app, [record(1, "三面", "通过")]).kind, "next-round");
assert.equal(progress(app, [record(1, "三面", "通过")]).nextRound, "");
assert.equal(progress(app, [record(1, "一面", "未通过")]).kind, "history");
assert.equal(progress(app, []).kind, "unscheduled");
assert.equal(effectiveStageState({ ...app, stageState: "待处理" }, [first]), "已完成，等待结果");
assert.equal(effectiveStageState({ ...app, stageState: "已完成" }, [second]), "待处理");
assert.equal(effectiveStageState({ ...app, currentStatus: "测评", stageState: "已安排" }, []), "已安排");
assert.equal(effectiveStageState({ ...app, currentStatus: "AI 面试", stageState: "已完成，等待结果" }, []), "已完成，等待结果");
console.log("Passed 19 interview workflow assertions (synthetic data only).");
